[project]
name = "lrcflow"
version = "0.1.0"
description = "Lighting Rendering and Compositing Workflow in Blender"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy>=4.0.0",
    "debugpy>=1.8.12",
    "pynvim>=0.5.2",
]
